// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#pragma once

// Handler
#define HANDLER_ERR_SUCCESS 0

// Plug-in
#define PLUGIN_ERR_SUCCESS 0
#define PLUGIN_ERR_INVALID_ARG -1
#define PLUGIN_ERR_MISSING_ENTRY_POINT -2
#define PLUGIN_ERR_INVALID_OUTPUT_BUFFER -3

// Response/Request
#define PLUGIN_ERR_INVALID_REQUEST_JSON -4
#define PLUGIN_ERR_INVALID_REQUEST_JSON_SCHEMA -5
#define PLUGIN_ERR_INVALID_RESPONSE_JSON -6
#define PLUGIN_ERR_INVALID_RESPONSE_JSON_SCHEMA -7

// Routing
#define PLUGIN_ERR_INVALID_PLUGIN_OPERATION -8
#define PLUGIN_ERR_INVALID_PLUGIN_HOST_TARGETTYPE -9
#define PLUGIN_ERR_INVALID_PLUGIN_HOST_OPERATION -10

// Targets

// MDM Server
#define PLUGIN_ERR_UNINITIALIZED_MDMSERVER -11
#define PLUGIN_ERR_INVALID_MDM_SERVER_OPERATION -12

// Raw Handlers
#define PLUGIN_ERR_INVALID_RAW_HANDLER -13
#define PLUGIN_ERR_INVALID_RAW_METHOD -14
#define PLUGIN_ERR_INVALID_RAW_HANDLER_HOST_OPERATION -15
#define PLUGIN_ERR_INVALID_RAW_HANDLER_ID -16

// Transport
#define PLUGIN_TRANSPORT_NOT_INITIALIZED -17 




#define PLUGIN_CREATE_REQUEST "Create Request"
#define PLUGIN_CREATE_SUCCESS_RESPONSE "Plugin Create Succeeded"
#define PLUGIN_CREATE_FAILED_RESPONSE "Plugin Create Failed"