#pragma once

enum DMErrors
{
    DM_ERROR_SUCCESS = 0,

    // DM Errors 1000-1999
    DM_ERROR_INVALID_JSON = 1000,
    DM_ERROR_INVALID_JSON_FORMAT,
    DM_ERROR_INVALID_REQUEST_JSON,
    DM_ERROR_INVALID_REQUEST_JSON_SCHEMA,
    DM_ERROR_INVALID_RESPONSE_JSON,
    DM_ERROR_INVALID_RESPONSE_JSON_SCHEMA,
    DM_ERROR_INVALID_DATETIME_FORMAT,
    DM_ERROR_INVALID_TIMEKIND,
    DM_ERROR_NOT_SUPPORTED,
    DM_ERROR_INVALID_DEPLOYMENT_STATUS,
    DM_ERROR_MISSING_XML_PATH,
    DM_ERROR_INVALID_CONNECTION_STATUS,
    DM_ERROR_INVALID_OPERATION,
    DM_ERROR_INVALID_SECTION,
    DM_ERROR_OPERATION_FAILED,
    DM_ERROR_INVALID_ARGUMENT,
    DM_ERROR_DPS_CLIENT_FAILED,

    DM_ERROR_PLUGIN_MANIFEST_INVALID_SCHEMA,
    DM_ERROR_PLUGIN_MANIFEST_MISSING_CODE_FILENAME,
    DM_ERROR_PLUGIN_MANIFEST_MISSING_OR_INVALID_DIRECT_ATTRIBUTE,
    DM_ERROR_PLUGIN_MANIFEST_MISSING_OR_INVALID_OUTOFPROC_ATTRIBUTE,
    DM_ERROR_PLUGIN_MANIFEST_MISSING_OR_INVALID_KEEPALIVE_ATTRIBUTE,
    DM_ERROR_PLUGIN_MANIFEST_INVALID_KEEPALIVE_VALUE,
    DM_ERROR_PLUGIN_MANIFEST_MISSING_CODE_DIRECT,
    DM_ERROR_PLUGIN_MANIFEST_MISSING_CODE_PUBLISH,
    DM_ERROR_PLUGIN_MANIFEST_MISSING_CODE_DEVICES,
    DM_ERROR_PLUGIN_MANIFEST_MISSING_CODE_INTERFACE_TYPE,
    DM_ERROR_PLUGIN_MANIFEST_INVALID_CODE_INTERFACE_TYPE,
    DM_ERROR_PLUGIN_HANDLER_INVALID_DEPENDENCY,

    // Plugin Errors 2000-2999
    DM_PLUGIN_ERROR_MISSING_ENTRY_POINT = 2000,
    DM_PLUGIN_ERROR_INVALID_OUTPUT_BUFFER,
    DM_PLUGIN_ERROR_INVALID_OPERATION,
    DM_PLUGIN_ERROR_INVALID_PLUGINHOST_TARGETTYPE,
    DM_PLUGIN_ERROR_INVALID_PLUGINHOST_OPERTION,
    DM_PLUGIN_ERROR_TRANSPORT_NOT_INITIALIZED,
    DM_PLUGIN_ERROR_INVALID_MANIFEST_SCHEMA,
    DM_PLUGIN_ERROR_MANIFEST_MISSING_CODE_FILENAME,
    DM_PLUGIN_ERROR_MANIFEST_MISSING_AGENT_PLUGIN_PROTOCOL_VERSION,
    DM_PLUGIN_ERROR_MANIFEST_MISSING_DIRECT_ATTRIBUTE,
    DM_PLUGIN_ERROR_MANIFEST_MISSING_OUTOFPROC_ATTRIBUTE,
    DM_PLUGIN_ERROR_MANIFEST_MISSING_KEEPALIVE_ATTRIBUTE,
    DM_PLUGIN_ERROR_MANIFEST_INVALID_KEEPALIVE_ATTRIBUTE,
    DM_PLUGIN_ERROR_INVALID_RAW_HANDLER,
    DM_PLUGIN_ERROR_INVALID_RAW_METHOD,
    DM_PLUGIN_ERROR_INVALID_RAW_HANDLER_HOST_OPERATION,
    DM_PLUGIN_ERROR_INVALID_RAW_HANDLER_ID,
    DM_PLUGIN_ERROR_UNINITIALIZED_TRANSPORT,
    DM_PLUGIN_ERROR_INVALID_PROTOCOL_VERSION,
    DM_PLUGIN_ERROR_INVALID_INTERFACE_VERSION,

    // MDM Server Errors 3000-3999
    DM_MDM_ERROR_UNINITIALIZED_MDMSERVER = 3000,
    DM_MDM_ERROR_INVALID_SERVER_OPERATION,

    // Shell|App Errors 4000-4999
    DM_SHELL_ERROR_NO_USER_PROCESS_FOUND = 4000,
    DM_SHELL_ERROR_APP_INSTALL_TASK_CANCELLED,
    DM_SHELL_ERROR_APP_INSTALL_FAILED,
    DM_SHELL_ERROR_APP_UNINSTALL_FAILED,
    DM_SHELL_ERROR_INVALID_DESIRED_MULTIPLE_FOREGROUND_APPS,
    DM_SHELL_ERROR_CONFLICT_UNINSTALL_FOREGROUND_APP,
    DM_SHEEL_ERROR_INVALID_DESIRED_NO_FOREGROUND_APPS
};
